amanavi2021/team-project-movies

src/index.html
src/index.js
src/js/modal.js
src/partials/footer.html
src/partials/modal.html
src/sass/components/_modal.scss
src/sass/index.scss

В модалці є 2 пустих блока, куди по логіці треба рендерити markup фільму і списку учасників. Можливе доопрацювання

Додає базову модалку Modal

---

.parcelrc
package-lock.json
package.json
src/index.js
src/js/apiService.js
src/js/renderFilms.js
src/partials/home-films-gallery.html
src/partials/home-header.html
src/templates/markupFilmMainPage.hbs

renderFilms

---

src/index.js
src/js/apiService.js
src/js/onLoad.js
src/js/renderFilms.js

в ApiService додано метод saveGenresToLocalStorage() в локал сторидж і рендер реалізовано через звертання до локал сториджа

saveGenresToLocalStorage

---

src/index.html
src/index.js
src/js/apiService.js
src/js/onLoad.js
src/js/renderFilms.js
src/js/searchByName.js

створила форму, у якій можна вводити пошук фільмів за іменем

search by name API

---

src/index.js
src/js/apiService.js
src/js/onLoad.js
src/js/renderFilms.js
src/js/service/localstorage.js
src/sass/utils/_base.scss

Додала окремо функцію роботи з локал сторедж і ще маленькі зміни по коду

loсalstorage

---

src/index.html
src/js/onLoad.js
src/js/renderFilms.js
src/js/searchByName.js

it is now connected to header form

search-by-name

---

src/js/renderFilms.js

if (poster_path != null) - додала перевірку, щоб не було пустих карток

renderFilm correction

---

src/js/team-members.js
src/sass/components/_modal.scss

Попросили вимкнути скролл сторінки коли модальне вікно активне

Вимикає scroll сторінки при відкритій модалці

---

src/js/modal.js

посали робити функцію для модального вікна при кліці на фільми

modal-on-movie-click

---

src/js/onLoad.js
src/js/service/refs.js
src/js/trailerplayer.js
src/partials/home-films-gallery.html
src/sass/utils/_gallery.scss
src/sass/utils/_visually-hidden.scss

Зробила запуск трейлера під різні екрани, зупинку ESC і клік на backdrop

trailer correction

---

src/js/searchByName.js
src/partials/home-films-gallery.html
src/sass/utils/_gallery.scss

Зробила зміни, щоб запускался трейлер при пагінації і після пошуку за назвою

trailer changes

---

src/js/modal.js
src/js/renderFilms.js

backdrop_path додала, але в HBS не міняла. Помилку знайшла, чомусь зайвий визов функціі renderList(); без аргументів був...

fixed modal bug

---

src/js/modal.js
src/js/trailerplayer.js
src/sass/components/_modal.scss
src/sass/utils/_gallery.scss
src/templates/markup-modal-movie.hbs

small correction? + по аналогії програвач з модалки, якщо хтось зробить більш гарно, то приберемо

correction

---

src/js/apiService.js
src/js/modal.js
src/js/onLoad.js
src/js/searchByName.js
src/js/service/refs.js
src/js/trailerplayer.js
src/my-library.js
src/sass/utils/_gallery.scss
src/templates/markup-modal-movie.hbs
src/templates/markupFilmMainPage.hbs

поправила щоб трейлер запускався з будь-якого місця, де є кнопка PLAY

trailer bug-fixed

---

src/js/onLoad.js
src/js/service/play-btn-delay.js
src/js/trailerplayer.js
src/sass/utils/_gallery.scss
src/templates/markup-modal-movie.hbs
src/templates/markupFilmMainPage.hbs

Додала функцію, щоб кнопка зявлялася після картинки, а не раніше..

play-btn-fix

---

src/js/modal.js
src/js/trailerplayer.js

Прибрала помилку з консоля при закритті модалки

player-bug-fix

---

src/partials/modal.html
src/sass/components/_footer.scss

Додає area-label для button close на модалку з текстовим описом кнопки. Прибирає margin-top у футера, тому що пагінацію перенесли вниз і там є відступи

Footer style

---

src/js/pagination-search.js
src/js/paginationIn-library.js
src/js/trailerplayer.js

додала кнопку трейлера в функціі для інших сторінок, повино зараз бути на всіх

btn-trailer

---

src/js/apiService.js
src/js/modal.js
src/js/service/play-btn-delay.js
src/templates/markup-modal-movie.hbs
src/templates/markupFilmMainPage.hbs

// Кнопка PLAY з'являється  в модалці після картинки і + нотіфікатор, колт фільм не знайдено

No-film notification

---

src/sass/components/_header.scss
src/sass/utils/_language-changer.scss
src/templates/markup-modal-movie-ua.hbs

Перемикач мов на головній розташовано корректно

language main page

---

src/js/language-changer.js
src/sass/utils/_theme-changer.scss

fix theme btn

---

src/js/modal.js
src/partials/home-films-gallery.html
src/partials/my-library-film-gallery.html
src/sass/components/_header.scss
src/sass/utils/_gallery.scss
src/templates/markupFilmMainPage.hbs

refs.filmClick.addEventListener('touchstart', onClickOpen); // тест для мобільки

тест touchstart

---

src/js/modal.js
src/js/service/catcherror.js
src/sass/utils/_theme-changer.scss

if (
document.querySelector('.nav__link--current').textContent === 'Home' ||
'Головна'
) - НЕ ВІРНО

modal-bug-fix

---

src/js/modal.js
src/sass/utils/_base.scss

додала   transition: background-image 250ms ease-in-out;
В модалці змінили коли очищення , згідно зауваження

minor-changes

---

src/js/modal.js
src/js/onLoad.js
src/js/searchByName.js
src/js/service/ontouch-scroll-check.js
src/my-library.js

додала фукцію перевірки для мобілки, щоб картинка відкривалася по touch а не по scroll . Але ще треба тестити

mobile touch

---

src/index.html
src/my-library.html
src/partials/my-library-film-gallery.html
src/sass/components/_footer.scss
src/sass/utils/_base.scss
src/sass/utils/_theme-changer.scss

transition for color and footer

trans for color and footer

---

src/partials/home-header.html
src/partials/modal.html
src/partials/my-library-header.html
src/templates/markup-modal-movie-ua.hbs
src/templates/markup-modal-movie.hbs

Reverts amanavi2021/team-project-movies#110

Revert "bugfixed"
